name: Build/Release

on: 
  repository_dispatch:

jobs:
  release-wiin-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Check out SRC Git repository
        uses: actions/checkout@v2
        with:
          repository: 'HavenCoreNetwork/Launcher'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        uses: nick-invision/retry@v2
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        with:
          timeout_minutes: 5
          max_attempts: 3
          shell: bash
          command: npm run dist -- -p always
  release-lin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        uses: nick-invision/retry@v2
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        with:
          timeout_minutes: 5
          max_attempts: 3
          shell: bash
          command: npm run dist -- -p always
